http:
  routers:
    gateway:
      rule: "PathPrefix(`/mcp`) || PathPrefix(`/.well-known/mcp-manifest.json`) || PathPrefix(`/api/gateway`)"
      service: gateway
      entryPoints:
        - web
    
    dashboard-router:
      rule: "PathPrefix(`/dashboard`)"
      service: dashboard
      entryPoints:
        - web
        
    traefik-api:
      rule: "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - web

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://gateway:8090"
    
    dashboard:
      loadBalancer:
        servers:
          - url: "http://dashboard:80"