services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      GATEWAY_PORT: 8090
      MCP_GATEWAY_API_KEY: mcp-gateway-default-key
      MCP_SERVERS: ""
    ports:
      - '8090:8090'
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge