version: '3.8'
services:
  traefik:
    image: traefik:v2.10
    command:
      - '--entrypoints.web.address=:8080'
      - '--providers.docker=false'
      - '--providers.file.directory=/etc/traefik/dynamic'
      - '--providers.file.watch=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
    ports:
      - '8081:8080'
    networks:
      - mcp_network
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    environment:
      NODE_ENV: production
      GATEWAY_PORT: '8090'
      MCP_HOME: /app/.mcp-platform
      MCP_GATEWAY_API_KEY: ${MCP_GATEWAY_API_KEY:-mcp-gateway-default-key}
    volumes:
      - ${HOME}/.mcp-platform:/app/.mcp-platform
    ports:
      - '8090:8090'
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.gateway.rule=PathPrefix(`/mcp`) ||
        PathPrefix(`/.well-known/mcp-manifest.json`) ||
        PathPrefix(`/api/gateway`)
      - traefik.http.services.gateway.loadbalancer.server.port=8090
      - >-
        traefik.http.routers.gateway-manifest.rule=Path(`/.well-known/mcp-manifest.json`)
      - traefik.http.routers.gateway-api.rule=PathPrefix(`/api/gateway`)
    networks:
      - mcp_network
    restart: unless-stopped
networks:
  mcp_network:
    driver: bridge
volumes: {}
